# Copyright (c) 2013-2017 by appPlant GmbH. All rights reserved.
#
# @APPPLANT_LICENSE_HEADER_START@
#
# This file contains Original Code and/or Modifications of Original Code
# as defined in and that are subject to the Apache License
# Version 2.0 (the 'License'). You may not use this file except in
# compliance with the License. Please obtain a copy of the License at
# http://opensource.org/licenses/Apache-2.0/ and read it before using this
# file.
#
# The Original Code and all software distributed under the License are
# distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
# EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
# INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
# Please see the License for the specific language governing rights and
# limitations under the License.
#
# @APPPLANT_LICENSE_HEADER_END@

language: objective-c
osx_image: xcode8.2

branches:
  only:
  - master
  - /^feature\//
  - /^bug\//

node_js:
- 6

notifications:
  email: false

matrix:
  fast_finish: true

before_install:
- xcrun simctl delete 79C525D3-2383-4201-AC3A-81810F9F4E03

install:
- npm install
- npm install -g cordova
- brew install gradle
- brew install android-sdk
- ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk -a -u -t "tools,platform-tools,build-tools-25.0.2,android-25,extra-android-m2repository"

before_script:
- cordova create myApp org.apache.cordova.myApp myApp
- cd myApp
- sed -i -r 's:\(<content.*\):\1<preference name="android-targetSdkVersion" value="16" />:' config.xml
- cordova platform add android@latest browser@latest ios@latest
- cordova plugin add cordova-plugin-background-mode --searchpath $TRAVIS_BUILD_DIR
- cordova platform ls
- cordova plugin ls

script:
- cordova build android
- cordova build browser
- cordova build ios
- cordova plugin add cordova-plugin-crosswalk-webview
- cordova plugin add cordova-plugin-wkwebview-engine
- cordova build android
- cordova build ios
