export const UI_SHOW_SPEED_SETTING_WINDOW = 'UI_SHOW_SPEED_SETTING_WINDOW';
export const UI_HIDE_SPEED_SETTING_WINDOW = 'UI_HIDE_SPEED_SETTING_WINDOW';
export const UI_SHOW_SHARE_WINDOW = 'UI_SHOW_SHARE_WINDOW';
export const UI_SHOW_SLEEPTIMER_WINDOW = 'UI_SHOW_SLEEPTIMER_WINDOW';


export const UI_SHOW_LOGIN = 'UI_SHOW_LOGIN';
export const UI_HIDE_LOGIN = 'UI_HIDE_LOGIN';
export const UI_SHOW_FULLPLAYER = 'UI_SHOW_FULLPLAYER';
export const UI_HIDE_FULLPLAYER = 'UI_HIDE_FULLPLAYER';

export const USER_SYNCING = 'USER_SYNCING';

export const WALLET_SYNCING = 'WALLET_SYNCING';
export const WALLET_SYNC_COMPLETE = 'WALLET_SYNC_COMPLETE';

export const WALLET_INVOICE_LOAD = 'WALLET_INVOICE_LOAD';
export const WALLET_INVOICE_SUCCESS = 'WALLET_INVOICE_SUCCESS';
export const WALLET_INVOICE_ERROR = 'WALLET_INVOICE_ERROR';

export const UI_SHOW_WALLET_WINDOW = 'UI_SHOW_WALLET_WINDOW';