export const UI_SHOW_SPEED_SETTING_WINDOW = 'UI_SHOW_SPEED_SETTING_WINDOW';
export const UI_HIDE_SPEED_SETTING_WINDOW = 'UI_HIDE_SPEED_SETTING_WINDOW';
export const UI_SHOW_SHARE_WINDOW = 'UI_SHOW_SHARE_WINDOW';
export const UI_SHOW_SLEEPTIMER_WINDOW = 'UI_SHOW_SLEEPTIMER_WINDOW';


export const UI_SHOW_LOGIN = 'UI_SHOW_LOGIN';
export const UI_HIDE_LOGIN = 'UI_HIDE_LOGIN';
export const UI_SHOW_FULLPLAYER = 'UI_SHOW_FULLPLAYER';
export const UI_HIDE_FULLPLAYER = 'UI_HIDE_FULLPLAYER';



export const USER_SYNCING = 'USER_SYNCING';